=== AlexJF/eclim/src/installer/resources/dependencies.dtd
<!ELEMENT dependencies (feature+)>

<!ELEMENT feature (dependency+)>
<!ATTLIST feature id ID #REQUIRED>

<!ELEMENT dependency (site+)>
<!ATTLIST dependency id ID #REQUIRED>
<!ATTLIST dependency version CDATA #REQUIRED>
<!ATTLIST dependency manual (true|false) #IMPLIED>

<!ELEMENT site EMPTY>
<!ATTLIST site url CDATA #REQUIRED>

=== AlexJF/eclim/src/installer/resources/dependencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dependencies SYSTEM "dependencies.dtd">
<dependencies primary="http://download.eclipse.org/releases/helios/">
  <feature id="cdt">
    <dependency id="org.eclipse.cdt" version="7.0.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
      <!--site url="http://download.eclipse.org/tools/cdt/releases/helios/"/-->
    </dependency>
  </feature>

  <feature id="dltk">
    <dependency id="org.eclipse.dltk.core" version="2.0.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
    </dependency>
  </feature>

  <feature id="dltkruby">
    <dependency id="org.eclipse.dltk.ruby" version="2.0.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
    </dependency>
  </feature>

  <feature id="jdt">
    <dependency id="org.eclipse.jdt" version="3.6.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
    </dependency>
  </feature>

  <feature id="pdt">
    <dependency id="org.eclipse.php" version="2.2.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
    </dependency>
  </feature>

  <feature id="wst">
    <dependency id="org.eclipse.wst.web_ui.feature" version="3.2.0">
      <site url="http://download.eclipse.org/releases/helios/"/>
      <!--site url="http://download.eclipse.org/webtools/updates/"/-->
    </dependency>
  </feature>
</dependencies>
